apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab28-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/VuVanPhong123/TRACK2_Day28_2A202601647_VuVanPhong.git
    targetRevision: refs/tags/day28-vu-van-phong-v2
    path: deploy/kubernetes/base
  destination:
    server: https://kubernetes.default.svc
    namespace: lab28
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
